name: Merge Conflict Notification

on:
  pull_request:
  
jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch branches
        run: |
          git fetch origin

      - name: Check for merge conflicts
        run: |
          BASE=$(git merge-base origin/main "${{ github.event.pull_request.head.sha }}")
          CONFLICTS=$(git diff --name-only "$BASE" "${{ github.event.pull_request.head.sha }}")
          if [[ -n "$CONFLICTS" ]]; then
            echo "Merge conflict detected in PR ${{ github.event.pull_request.number }}"
          fi

      - name: Send notification
        run: |
          if [[ -n "$CONFLICTS" ]]; then
            curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Merge conflict detected in PR ${{ github.event.pull_request.number }}\"}" https://hooks.slack.com/services/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
          fi
