name: Merge Conflict Notification

on:
  pull_request:
    types:
      - synchronize

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Check for merge conflicts
        run: |
          git fetch origin pull/${{ github.event.pull_request.number }}/merge
          git diff --name-only origin/main...FETCH_HEAD

      - name: Send notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [[ -n $(git diff --name-only origin/main...FETCH_HEAD) ]]; then
            curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Merge conflict detected in PR ${{ github.event.pull_request.number }}\"}" $SLACK_WEBHOOK_URL
          fi
