name: Merge Conflict Notification

on:
  pull_request:
  
jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Git
      run: sudo apt-get -y install git

    - name: Check for merge conflicts
      id: merge-check
      run: |
        git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge:
        git diff --name-only FETCH_HEAD...HEAD | xargs test -e

    - name: Send notification to Slack
      if: steps.merge-check.outputs.stdout
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        args: '{"text": "A merge conflict occurred in PR ${{ github.event.pull_request.number }}."}'
