name: Merge Conflict Notification

on:
  push:
    branches:
      - master

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq -y

    - name: Check for merge conflict
      run: |
        conflict_files=$(git diff --name-only --diff-filter=U)
        if [ -n "$conflict_files" ]; then
          echo "Merge conflict detected!"
          echo "The following files have conflicts:"
          echo "$conflict_files"
          echo "::set-output name=conflict_files::$conflict_files"
        else
          echo "No merge conflict detected."
        fi

    - name: Send notification to Slack
      if: ${{ steps.check_conflict.outputs.conflict_files }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        conflict_files=${{ steps.check_conflict.outputs.conflict_files }}
        message="Merge conflict detected in the following files:${conflict_files}"
        payload="{\"text\": \"${message}\"}"
        curl -X POST -H 'Content-type: application/json' --data "${payload}" "${SLACK_WEBHOOK_URL}"
