name: Merge Conflict Notification

on:
  push:
    branches:
      - main

jobs:
  merge_conflict_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Git
        run: |
          sudo apt-get update && sudo apt-get install git -y

      - name: Check for merge conflict
        run: |
          git checkout main
          git pull origin main
          git checkout ${{ github.sha }}
          git merge main
          if [[ $? -ne 0 ]]; then
            echo "Merge conflict detected."
            echo "Sending notification to Slack..."
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Merge conflict detected in branch '${{ github.ref }}'."}' ${{ secrets.SLACK_WEBHOOK_URL }}
            exit 1
          fi
